[package]
name = "mdrend"
version = "0.1.0"
authors = ["magdi <migzzat@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
pulldown-cmark = "0.6.0"
maud = "0.21.0"
